name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Check, test, rustfmt and clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust, clippy and rustfmt
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Check
        run: |
          cargo check --workspace --all-features

      - name: Test
        run: |
          cargo test --workspace --all-features

      - name: Rustfmt
        run: |
          cargo fmt --all --check

      - name: Clippy
        run: |
          cargo clippy --workspace --all-features --all-targets --tests -- --deny warnings --verbose
